upload_max_filesize = 50M
post_max_size = 50M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

opcache.enable = 1
opcache.validate_timestamps = 0
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 192
opcache.interned_strings_buffer = 16
